pipeline {
  agent any
  stages {
    stage('Export feature files') {
      steps{
          step([$class: 'XrayExportBuilder', issues: 'CALC-207', serverInstance: '5b637012-9ba3-4005-afbe-7f11a19df03f'])
      }
    }
    stage('Run tests') {
      steps {
        echo 'Testing..'
      }
    }
    stage('Import results to Xray') {
      steps {
        step([$class: 'XrayImportBuilder', endpointName: '/cucumber/multipart', importFilePath: 'server/CucumberFlowXrayMasterMultipart/login-feature.json', importToSameExecution: 'true', projectKey: 'CALC', fixVersion: '1.2', revision: 'commit eee455', importInfo: 'server/CucumberFlowXrayMasterMultipart/my-test-exec-info.json', testImportInfo: 'server/CucumberFlowXrayMasterMultipart/my-test-import-info.json', inputInfoSwitcher: 'filePath', inputTestInfoSwitcher: 'filePath', serverInstance: '5b637012-9ba3-4005-afbe-7f11a19df03f'])
      }
    }
  }
}