pipeline {
  agent any
  stages {
    stage('Import results to Xray') {
      steps {
        step([$class: 'XrayImportBuilder', endpointName: '/junit', importFilePath: 'server/importJunitNewTestExec/xray-report.xml', importToSameExecution: 'true', projectKey: 'CALC', fixVersion: '1.2', revision: 'commit eee455', serverInstance: '5b637012-9ba3-4005-afbe-7f11a19df03f'])
      }
    }
  }
}