pipeline {
  agent any
  stages {
    stage('Import results to Xray (multipart)') {
        steps {
            step([$class: 'XrayImportBuilder', endpointName: '/junit/multipart', importFilePath: 'server/importJunitMultipart/*.xml', importToSameExecution: 'true', projectKey: 'CALC', serverInstance: '5b637012-9ba3-4005-afbe-7f11a19df03f', importInParallel: 'true', importInfo: 'server/importJunitMultipart/my-test-exec-info.json', testImportInfo: 'server/importJunitMultipart/my-test-import-info.json', inputInfoSwitcher: 'filePath', inputTestInfoSwitcher: 'filePath' ])
        }
    }
  }
}